### ISSUE TITLE
Setup configurations to run Fedora 3 exports for production data

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#125]
For this ticket, we want to enable the same functionality to export data from Fedora 3 from a deployed server instance, but using production data credentials instead of the Fedora 3 QA environment.

See prior work in #102

**Comment by jcrompton42** [comment]
submitted ticket to allow connections from hyrax test instance rather than fedora

**Comment by jcrompton42** [comment]
hyrax test instance can reach libfedprod1.library.emory.edu on port 8080. @bwatson78 please advise if any further action on my part is needed

**Comment by bwatson78** [comment]
I receive the following error when attempting an import from Prod:
```
WARN 12:23:00.432 (PhaseInterceptorChain) Interceptor for {http://fedora-commons.org/2011/07/definitions/types/}FedoraAPIAMTOMService#{http://fedora-commons.org/2011/07/definitions/types/}describeRepository has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:565) [cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:474) [cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:377) [cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:330) [cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96) [cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:135) [cxf-bundle-2.7.7.jar:2.7.7]
        at com.sun.proxy.$Proxy50.describeRepository(Unknown Source) [na:na]
        at org.fcrepo.client.utility.export.Export.main(Export.java:253) [fcrepo-client-admin-3.8.1.jar:na]
Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '401: Unauthorized' when communicating with http://libfedprod1.library.emory.edu:8080/fedora/services/accessMTOM
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1542) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1502) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1309) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:627) ~[cxf-bundle-2.7.7.jar:2.7.7]
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62) ~[cxf-bundle-2.7.7.jar:2.7.7]
        ... 9 common frames omitted
Error  : javax.xml.ws.WebServiceException: Could not send Message.Could not send Message../lib/fedora/migrate_fedora3_objects.rb:48:in `initialize': No such file or directory @ rb_sysopen - ./emory_q4fd0.xml (Errno::ENOENT)
        from ./lib/fedora/migrate_fedora3_objects.rb:48:in `open'
        from ./lib/fedora/migrate_fedora3_objects.rb:48:in `pull_pid_xml'
        from ./lib/fedora/migrate_fedora3_objects.rb:34:in `block in run'
        from ./lib/fedora/migrate_fedora3_objects.rb:31:in `each'
        from ./lib/fedora/migrate_fedora3_objects.rb:31:in `run'
        from ./lib/fedora/migrate_fedora3_objects.rb:105:in `<main>'
```

**Comment by bwatson78** [comment]
I was able to run import script after @jcrompton42 setup username/password for production Fedora.
