### ISSUE TITLE
BUG: Cannot upload a banner or logo file for a Collection's branding.

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#412]
Attempting to save banner image in https://oe24-arch.libraries.emory.edu/dashboard/collections/be0ee0ca-67e1-4ca7-9600-fd629b37d0e9/edit?locale= produces the following error:
```
I, [2024-07-17T13:06:24.176412 #7412]  INFO -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] Started PATCH "/uploads/" for 10.65.89.69 at 2024-07-17 13:06:24 +0000
I, [2024-07-17T13:06:24.178136 #7412]  INFO -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] Processing by Hyrax::UploadsController#create as JSON
I, [2024-07-17T13:06:24.178288 #7412]  INFO -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   Parameters: {"authenticity_token"=>"GRfmxY5XoYKCtvBckrZm4tjwd8MT9jjJj9WbZIhZ4XBe0IBx/liIBNHEvp5JgCfL/ialvfKM/KH6LAc0xlwYyQ==", "collection"=>{"tit
le"=>["Test Collection", ""], "creator"=>["dklddwjkd", ""], "description"=>["sdqfw2f", ""], "emory_ark"=>[""], "holding_repository"=>"Emory University. Library", "institution"=>"Emory University", "internal_rights_note"=>"", "system_of_
record_ID"=>"", "administrative_unit"=>"", "contact_information"=>"", "keyword"=>[""], "rights_notes"=>[""], "staff_notes"=>[""], "subject"=>[""], "subject_geo"=>[""], "subject_names"=>[""], "notes"=>[""], "visibility"=>"restricted"}, "
type"=>"", "stay_on_edit"=>"true", "collection_type_gid"=>"gid://dlp-self-deposit/Hyrax::CollectionType/2", "permission_template"=>{"access_grants_attributes"=>{"0"=>{"agent_type"=>"group", "agent_id"=>"", "access"=>""}}}, "referer_anch
or"=>"#branding", "files"=>[#<ActionDispatch::Http::UploadedFile:0x00007f70abe52630 @tempfile=#<Tempfile:/tmp/RackMultipart20240717-7412-qht5c.jpg>, @original_filename="ET.jpg", @content_type="image/jpeg", @headers="Content-Disposition:
 form-data; name=\"files[]\"; filename=\"ET.jpg\"\r\nContent-Type: image/jpeg\r\n">]}
D, [2024-07-17T13:06:24.181995 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mHyrax::Feature Load (0.7ms)ESC[0m  ESC[1mESC[34mSELECT "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORD
ER BY "hyrax_features"."id" ASC LIMIT $2ESC[0m  [["key", "read_only"], ["LIMIT", 1]]
D, [2024-07-17T13:06:24.186343 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mUser Load (0.8ms)ESC[0m  ESC[1mESC[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2ESC[0m 
 [["id", 1], ["LIMIT", 1]]
D, [2024-07-17T13:06:24.189705 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mRole Load (0.7ms)ESC[0m  ESC[1mESC[34mSELECT "roles".* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id
" WHERE "roles_users"."user_id" = $1ESC[0m  [["user_id", 1]]
D, [2024-07-17T13:06:24.189920 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] Usergroups are ["public", "admin", "registered"]
D, [2024-07-17T13:06:24.191730 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mRole Exists? (0.9ms)ESC[0m  ESC[1mESC[34mSELECT 1 AS one FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_
id" WHERE "roles_users"."user_id" = $1 AND "roles"."name" = $2 LIMIT $3ESC[0m  [["user_id", 1], ["name", "admin"], ["LIMIT", 1]]
D, [2024-07-17T13:06:24.193564 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mHyrax::Feature Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORD
ER BY "hyrax_features"."id" ASC LIMIT $2ESC[0m  [["key", "transfer_works"], ["LIMIT", 1]]
D, [2024-07-17T13:06:24.195007 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mHyrax::Feature Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORD
ER BY "hyrax_features"."id" ASC LIMIT $2ESC[0m  [["key", "proxy_deposit"], ["LIMIT", 1]]
D, [2024-07-17T13:06:24.202317 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mTRANSACTION (1.0ms)ESC[0m  ESC[1mESC[35mBEGINESC[0m
D, [2024-07-17T13:06:24.203764 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mHyrax::UploadedFile Create (1.1ms)ESC[0m  ESC[1mESC[32mINSERT INTO "uploaded_files" ("user_id", "created_at", "updated_at") VALUES ($
1, $2, $3) RETURNING "id"ESC[0m  [["user_id", 1], ["created_at", "2024-07-17 13:06:24.200661"], ["updated_at", "2024-07-17 13:06:24.200661"]]
D, [2024-07-17T13:06:24.206768 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   ESC[1mESC[36mTRANSACTION (2.2ms)ESC[0m  ESC[1mESC[35mCOMMITESC[0m
D, [2024-07-17T13:06:24.207522 #7412] DEBUG -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   Rendering /opt/dlp-selfdeposit/shared/bundle/ruby/3.2.0/gems/hyrax-5.0.1/app/views/hyrax/uploads/create.json.jbuilder
I, [2024-07-17T13:06:24.207902 #7412]  INFO -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   Rendered /opt/dlp-selfdeposit/shared/bundle/ruby/3.2.0/gems/hyrax-5.0.1/app/views/hyrax/uploads/create.json.jbuilder (Duration: 0.3ms | Allocation
s: 159)
I, [2024-07-17T13:06:24.208248 #7412]  INFO -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] Completed 500 Internal Server Error in 30ms (ActiveRecord: 8.6ms | Allocations: 4484)
F, [2024-07-17T13:06:24.209842 #7412] FATAL -- : [bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] ActionView::Template::Error (undefined method `filename' for nil:NilClass):
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     1: # frozen_string_literal: true
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     2: json.files [@upload] do |uploaded_file|
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     3:   json.id uploaded_file.id
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     4:   json.name uploaded_file.file.file.filename
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     5:   json.size uploaded_file.file.file.size
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     6:   # TODO: implement these
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]     7:   # json.url  "/uploads/#{uploaded_file.id}"
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7]   
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] hyrax (5.0.1) app/views/hyrax/uploads/create.json.jbuilder:4
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] jbuilder (2.12.0) lib/jbuilder.rb:343:in `block (2 levels) in _map_collection'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] jbuilder (2.12.0) lib/jbuilder.rb:350:in `_scope'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] jbuilder (2.12.0) lib/jbuilder.rb:41:in `set!'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] jbuilder (2.12.0) lib/jbuilder/jbuilder_template.rb:133:in `set!'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] jbuilder (2.12.0) lib/jbuilder.rb:73:in `method_missing'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] hyrax (5.0.1) app/views/hyrax/uploads/create.json.jbuilder:2
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/base.rb:247:in `public_send'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/base.rb:247:in `_run'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/template.rb:154:in `block in render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] activesupport (6.1.7.8) lib/active_support/notifications.rb:205:in `instrument'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/template.rb:345:in `instrument_render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/template.rb:152:in `render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] activesupport (6.1.7.8) lib/active_support/notifications.rb:203:in `block in instrument'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] activesupport (6.1.7.8) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] activesupport (6.1.7.8) lib/active_support/notifications.rb:203:in `instrument'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/template_renderer.rb:11:in `render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/rendering.rb:117:in `block in _render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/base.rb:273:in `in_rendering_context'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/rendering.rb:116:in `_render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/streaming.rb:218:in `_render_template'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionview (6.1.7.8) lib/action_view/rendering.rb:103:in `render_to_body'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/abstract_controller/rendering.rb:25:in `render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/rendering.rb:36:in `render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] /usr/local/rbenv/versions/3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] activesupport (6.1.7.8) lib/active_support/core_ext/benchmark.rb:14:in `ms'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] activerecord (6.1.7.8) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/instrumentation.rb:45:in `render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] <internal:kernel>:90:in `tap'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[bcbe1bd6-9e2a-4f4a-a77e-ece7a3693cb7] actionpack (6.1.7.8) lib/abstract_controller/base.rb:228:in `process_action'
```

**Comment by eporter23** [comment]
I was able to assign a banner to a brand new collection in oe24-test.
